<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Disbursement Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }
        .header p {
            margin: 5px 0;
            font-size: 14px;
        }
        .filters {
            margin-bottom: 20px;
            font-size: 11px;
        }
        .filters strong {
            display: inline-block;
            margin-right: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            text-align: center;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .no-data {
            text-align: center;
            padding: 50px;
            font-size: 14px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LYDO Scholarship Disbursement Report</h1>
        <p>Tagoloan, Misamis Oriental</p>
        <p>Generated on: {{ date('F d, Y') }}</p>
    </div>

    @if(!empty($filters))
    <div class="filters">
        <strong>Applied Filters:</strong>
        {{ implode(' | ', $filters) }}
    </div>
    @endif

    @if($disbursements->count() > 0)
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Scholar Name</th>
                <th style="width: 15%;">Barangay</th>
                <th style="width: 15%;">Academic Year</th>
                <th style="width: 15%;">Semester</th>
                <th style="width: 15%;">Amount</th>
                <th style="width: 10%;">Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($disbursements as $index => $disbursement)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $disbursement->full_name }}</td>
                <td>{{ $disbursement->applicant_brgy }}</td>
                <td class="text-center">{{ $disbursement->disburse_acad_year }}</td>
                <td class="text-center">{{ $disbursement->disburse_semester }}</td>
                <td class="text-right">₱{{ number_format($disbursement->disburse_amount, 2) }}</td>
                <td class="text-center">{{ \Carbon\Carbon::parse($disbursement->disburse_date)->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align: right; font-weight: bold;">Total Amount:</td>
                <td class="text-right" style="font-weight: bold;">₱{{ number_format($disbursements->sum('disburse_amount'), 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>Total Records: {{ $disbursements->count() }}</p>
        <p>Report generated by LYDO Scholarship System</p>
    </div>
    @else
    <div class="no-data">
        <p>No disbursement records found matching the specified criteria.</p>
    </div>
    @endif
</body>
</html>
