<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Scholars Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }
        .header p {
            margin: 5px 0;
            font-size: 14px;
        }
        .filters {
            margin-bottom: 20px;
            font-size: 11px;
        }
        .filters strong {
            display: inline-block;
            margin-right: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #333;
            padding: 6px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            text-align: center;
            font-size: 11px;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .no-data {
            text-align: center;
            padding: 50px;
            font-size: 14px;
            color: #666;
        }
        .status-active {
            color: #28a745;
            font-weight: bold;
        }
        .status-inactive {
            color: #dc3545;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LYDO Scholarship Scholars Report</h1>
        <p>Tagoloan, Misamis Oriental</p>
        <p>Generated on: {{ date('F d, Y') }}</p>
    </div>

    @if(!empty($filters))
    <div class="filters">
        <strong>Applied Filters:</strong>
        {{ implode(' | ', $filters) }}
    </div>
    @endif

    @if($scholars->count() > 0)
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 20%;">Full Name</th>
                <th style="width: 15%;">School</th>
                <th style="width: 10%;">Course</th>
                <th style="width: 8%;">Year Level</th>
                <th style="width: 10%;">Barangay</th>
                <th style="width: 10%;">Academic Year</th>
                <th style="width: 8%;">Status</th>
                <th style="width: 14%;">Date Activated</th>
            </tr>
        </thead>
        <tbody>
            @foreach($scholars as $index => $scholar)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>
                    {{ $scholar->applicant_fname }}
                    @if($scholar->applicant_mname)
                        {{ $scholar->applicant_mname }}
                    @endif
                    {{ $scholar->applicant_lname }}
                    @if($scholar->applicant_suffix)
                        {{ $scholar->applicant_suffix }}
                    @endif
                </td>
                <td>{{ $scholar->applicant_school_name }}</td>
                <td>{{ $scholar->applicant_course }}</td>
                <td class="text-center">{{ $scholar->applicant_year_level }}</td>
                <td>{{ $scholar->applicant_brgy }}</td>
                <td class="text-center">{{ $scholar->applicant_acad_year }}</td>
                <td class="text-center">
                    <span class="status-{{ strtolower($scholar->scholar_status) }}">
                        {{ ucfirst($scholar->scholar_status) }}
                    </span>
                </td>
                <td class="text-center">
                    @if($scholar->date_activated)
                        {{ \Carbon\Carbon::parse($scholar->date_activated)->format('M d, Y') }}
                    @else
                        -
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Scholars: {{ $scholars->count() }}</p>
        <p>Report generated by LYDO Scholarship System</p>
    </div>
    @else
    <div class="no-data">
        <p>No scholar records found matching the specified criteria.</p>
    </div>
    @endif
</body>
</html>
